default: &default
  adapter: postgresql
  encoding: <%= ENV['DB_ENCODING'] || 'unicode' %>
  pool: 5
  database: <%= ENV['DB_NAME'] || 'blog_development' %>
  username: <%= ENV['DB_USER'] || 'postgres' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] || '' %>

development:
  <<: *default

test: &test
  <<: *default
  database: <%= ENV['DB_NAME'] || 'blog_test' %>

production:
  <<: *default

cucumber:
  database: <%= ENV['DB_NAME'] || 'blog_test' %>
  <<: *test
